### ISSUE TITLE
ActiveState Tk build fails

### ISSUE THREAD

**Issue by asb-capfan** [eserte/perl-tk#20]
There is an error with all PPM builds at ActiveState since Perl 5.18. That's the release when they moved to MinGW as compiler.

Can this be fixed? 
Without knowing any of C and compiling stuff, but should it be easier now to support PPM builds as we don't have to consider the Visual C++ specifics anymore?

Please find the build log here: http://ppm4.activestate.com/MSWin32-x86-64int/5.22/2200/S/SR/SREZIC/Tk-804.033.d/log-20150820T163105.txt?_ga=1.61890031.2132896762.1444146524
There is an overview over all ActiveState Perl versions here: http://code.activestate.com/ppm/Tk/
And finally, here is the release notes with the changes to the compiler: http://docs.activestate.com/activeperl/5.18/changes.html ("All Windows builds are now built with the MinGW compiler.")

**Comment by glenntanner3** [comment]
Tk is on the brink of not being supported by a freely downloadable version of ActiveState Perl. I have attempted to look into this myself, I think it's a problem when it comes to compiling something for PNG images. Worst problem is I dont know if I had correctly setup my build environment as finding the old tools and knowing if they are working is hard; there really isn't any clear documentation thats says "how to setup your own build system".

**Comment by asb-capfan** [comment]
The ActiveState team kindly investigated the topic and now all builds are working fine: http://code.activestate.com/ppm/Tk/ 
 :100:

**Comment by glenntanner3** [comment]
Great! Did they say what was wrong?

**Comment by asb-capfan** [comment]
Not directly. But I think you can have a look at the build logs to see what was changed.

**Comment by eserte** [comment]
It seems that a patch is applied. Open http://ppm4.activestate.com/MSWin32-x86-64int/5.18/1800/S/SR/SREZIC/Tk-804.033.d/log-20160203T151155.txt?_ga=1.130054857.731424636.1451823317 and search for the string "Applying 1 patch". I see some changes regarding png libs/includes and a `XS_INTERNAL`/`XS_EXTERNAL` change which I don't understand.
