### ISSUE TITLE
encGlue.c: undefined reference to `MAX' on Strawberry 5.32 (RT 133260)

### ISSUE THREAD

**Issue by bekuno** [eserte/perl-tk#69]
see https://rt.cpan.org/Public/Bug/Display.html?id=133260
and https://stackoverflow.com/questions/63693574/strawberryperl-5-32-0-1-tk-cpan-error-undefined-reference-to-max

**Comment by chrstphrchvz** [comment]
Fixed in 804.035_501/804.036: c3e65df
