### ISSUE TITLE
ptked is not UTF-8

### ISSUE THREAD

**Issue by cessenat** [eserte/perl-tk#83]
When installing perl-tk using spack, post_install hook fails since ptked is not an UTF-8 file.
I submittted a Pull Request to spack for that, but meanwhile I think one could either modify the copyright (&copy;) symbol to (c) as in the other files of perl-tk, or convert to UTF-8.
I join the converted file.

[ptked.gz](https://github.com/eserte/perl-tk/files/6636131/ptked.gz)

**Comment by eserte** [comment]
Note that also a `use utf8;` is required, otherwise Help > About would show mojibake instead of the copyright sign.
However, for simplicity and consistency I just modified the character to `(c)`.

**Comment by cessenat** [comment]
OK, thank you very much !
Cheers.
